apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-job
  namespace: default
  labels:
    app: cron-job
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        metadata:
          labels:
            app: cron-job
        spec:
          restartPolicy: OnFailure
          containers:
            - name: cron-job
              image: cron-job:0.0.1-SNAPSHOT
              imagePullPolicy: Always
              env:
                - name: SPRING_PROFILES_ACTIVE
                  value: "prod"
                - name: SPRING_DATASOURCE_URL
                  valueFrom:
                    secretKeyRef:
                      name: cron-job-db-secret
                      key: url
                - name: SPRING_DATASOURCE_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: cron-job-db-secret
                      key: username
                - name: SPRING_DATASOURCE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: cron-job-db-secret
                      key: password
              resources:
                requests:
                  memory: "256Mi"
                  cpu: "250m"
                limits:
                  memory: "512Mi"
                  cpu: "500m"
