spring.application.name=cron-job

#spring.main.web-application-type=none
#spring.batch.job.enabled=true

# database config
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.batch.initialize-schema=always


logging.level.org.springframework.scheduling=DEBUG
logging.level.org.springframework.batch=DEBUG
