apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: cron-job
  namespace: default
  labels:
    apps.tanzu.vmware.com/workload-type: worker
    app.kubernetes.io/part-of: cron-job
spec:
  source:
    git:
      url: https://github.com/steve-kouna/cron-job-test
      ref:
        branch: main
  build:
    env:
      - name: BP_JVM_VERSION
        value: "21"
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: "prod"
    - name: SPRING_DATASOURCE_URL
      valueFrom:
        secretKeyRef:
          name: cron-job-db-secret
          key: url
    - name: SPRING_DATASOURCE_USERNAME
      valueFrom:
        secretKeyRef:
          name: cron-job-db-secret
          key: username
    - name: SPRING_DATASOURCE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: cron-job-db-secret
          key: password
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
